In [62]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [171]:
car=pd.read_csv('cardekho.csv')

In [172]:
car.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0

In [173]:
car.duplicated().sum()

np.int64(1202)

In [174]:
car.shape

(8128, 12)

In [175]:
car[car.duplicated()]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
291,Hyundai Grand i10 Sportz,2017,450000,35000,Petrol,Individual,Manual,First Owner,18.90,1197.0,82,5.0
296,Maruti Swift VXI,2012,330000,50000,Petrol,Individual,Manual,Second Owner,18.60,1197.0,85.8,5.0
370,Jaguar XE 2016-2019 2.0L Diesel Prestige,2017,2625000,9000,Diesel,Dealer,Automatic,First Owner,13.60,1999.0,177,5.0
371,Lexus ES 300h,2019,5150000,20000,Petrol,Dealer,Automatic,First Owner,22.37,2487.0,214.56,5.0
372,Jaguar XF 2.0 Diesel Portfolio,2017,3200000,45000,Diesel,Dealer,Automatic,First Owner,19.33,1999.0,177,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7987,Renault Captur 1.5 Diesel RXT,2018,1265000,12000,Diesel,Individual,Manual,First Owner,20.37,1461.0,108.45,5.0
7988,Maruti Ciaz Alpha Diesel,2019,1025000,32000,Diesel,Individual,Manual,First Owner,28.09,1248.0,88.5,5.0
8117,Maruti Swift Dzire VDI,2015,625000,50000,Diesel,Individual,Manual,First Owner,26.59,1248.0,74,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0

In [176]:
car=car.drop_duplicates().reset_index(drop=True)

In [177]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6926 entries, 0 to 6925
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                6926 non-null   object
 1   year                6926 non-null   int64
 2   selling_price       6926 non-null   int64
 3   km_driven           6926 non-null   int64
 4   fuel                6926 non-null   object
 5   seller_type         6926 non-null   object
 6   transmission        6926 non-null   object
 7   owner               6926 non-null   object
 8   mileage(km/ltr/kg)  6718 non-null   float64
 9   engine              6718 non-null   float64
 10  max_power           6721 non-null   object
 11  seats               6718 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 649.4+ KB

In [178]:
car.isnull().sum()

name                    0
year                    0
selling_price           0
km_driven               0
fuel                    0
seller_type             0
transmission            0
owner                   0
mileage(km/ltr/kg)    208
engine                208
max_power             205
seats                 208
dtype: int64

In [179]:
car.describe()

,year,selling_price,km_driven,mileage(km/ltr/kg),engine,seats
count,6926.000000,6.926000e+03,6.926000e+03,6718.00000,6718.000000,6718.000000
mean,2013.420300,5.172707e+05,7.399568e+04,19.46531,1430.891337,5.434653
std,4.078286,5.197670e+05,5.835810e+04,4.04915,493.493277,0.984230
min,1983.000000,2.999900e+04,1.000000e+00,0.00000,624.000000,2.000000
25%,2011.000000,2.500000e+05,4.000000e+04,16.80000,1197.000000,5.000000
50%,2014.000000,4.000000e+05,7.000000e+04,19.44000,1248.000000,5.000000
75%,2017.000000,6.335000e+05,1.000000e+05,22.50000,1498.000000,5.000000
max,2020.000000,1.000000e+07,2.360457e+06,42.00000,3604.000000,14.000000

In [180]:
car.dropna(inplace=True)
car.reset_index(drop=True, inplace=True)

In [181]:
car.shape

(6718, 12)

In [182]:
car=car.drop(['mileage(km/ltr/kg)', 'engine', 'max_power', 'seats', 'year', 'km_driven', 'seller_type', 'owner'], axis=1)

In [183]:
car['model']=car['name'].str.split().str.slice(0,3).str.join(' ')

In [186]:
car.head()

,name,selling_price,fuel,transmission,model,tags
0,Maruti Swift Dzire VDI,450000,Diesel,Manual,Maruti Swift Dzire,Maruti Swift Dzire VDI Diesel Manual
1,Skoda Rapid 1.5 TDI Ambition,370000,Diesel,Manual,Skoda Rapid 1.5,Skoda Rapid 1.5 TDI Ambition Diesel Manual
2,Honda City 2017-2020 EXi,158000,Petrol,Manual,Honda City 2017-2020,Honda City 2017-2020 EXi Petrol Manual
3,Hyundai i20 Sportz Diesel,225000,Diesel,Manual,Hyundai i20 Sportz,Hyundai i20 Sportz Diesel Diesel Manual
4,Maruti Swift VXI BSIII,130000,Petrol,Manual,Maruti Swift VXI,Maruti Swift VXI BSIII Petrol Manual

In [185]:
car['tags']=car['name']+" "+car['fuel']+" "+car['transmission']

In [188]:
car['tags']=car['tags'].apply(lambda x:x.lower())

In [189]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [190]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [191]:
car['tags']=car['tags'].apply(stem)

In [192]:
car.head()

,name,selling_price,fuel,transmission,model,tags
0,Maruti Swift Dzire VDI,450000,Diesel,Manual,Maruti Swift Dzire,maruti swift dzire vdi diesel manual
1,Skoda Rapid 1.5 TDI Ambition,370000,Diesel,Manual,Skoda Rapid 1.5,skoda rapid 1.5 tdi ambit diesel manual
2,Honda City 2017-2020 EXi,158000,Petrol,Manual,Honda City 2017-2020,honda citi 2017-2020 exi petrol manual
3,Hyundai i20 Sportz Diesel,225000,Diesel,Manual,Hyundai i20 Sportz,hyundai i20 sportz diesel diesel manual
4,Maruti Swift VXI BSIII,130000,Petrol,Manual,Maruti Swift VXI,maruti swift vxi bsiii petrol manual

In [132]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=500, stop_words='english')

In [194]:
vectors=cv.fit_transform(car['tags']).toarray()

In [195]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], shape=(6718, 50))

In [196]:
list(cv.get_feature_names_out())

['800',
 'ac',
 'alto',
 'asta',
 'automat',
 'bolero',
 'bs',
 'bsiii',
 'bsiv',
 'chevrolet',
 'citi',
 'crdi',
 'diesel',
 'dzire',
 'figo',
 'ford',
 'grand',
 'honda',
 'hyundai',
 'i10',
 'i20',
 'innova',
 'iv',
 'lx',
 'lxi',
 'magna',
 'mahindra',
 'manual',
 'maruti',
 'mt',
 'option',
 'petrol',
 'plu',
 'renault',
 'scorpio',
 'seater',
 'sportz',
 'swift',
 'sx',
 'tata',
 'tdi',
 'titanium',
 'toyota',
 'vdi',
 'verna',
 'volkswagen',
 'vx',
 'vxi',
 'wagon',
 'zdi']

In [199]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
price=sc.fit_transform(car[['selling_price']])

In [200]:
final_vectors = np.hstack((vectors, price))

In [201]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(final_vectors)
print(similarity)

[[1.         0.47158199 0.20420014 ... 0.18275541 0.3333549  0.83337141]
 [0.47158199 1.         0.28873961 ... 0.25838307 0.47139346 0.47154793]
 [0.20420014 0.28873961 1.         ... 0.44725004 0.20414565 0.20419125]
 ...
 [0.18275541 0.25838307 0.44725004 ... 1.         0.36517003 0.18272724]
 [0.3333549  0.47139346 0.20414565 ... 0.36517003 1.         0.3333576 ]
 [0.83337141 0.47154793 0.20419125 ... 0.18272724 0.3333576  1.        ]]

In [213]:
def recommend(model):
    car_index=car[car['model']==model].index[0]
    distance=similarity[car_index]
    car_list=sorted(list(enumerate(distance)), reverse=True, key=lambda x:x[1])[1:6]
    for i in car_list:
        print(car.iloc[i[0]]['model'])

In [216]:
recommend('Skoda Rapid 1.5')

Skoda Rapid Ultima
Skoda Octavia Ambiente
Skoda Rapid 1.6
Skoda Rapid 1.6
Skoda Rapid 1.5

In [218]:
import pickle
pickle.dump(similarity, open('similarity.pkl', 'wb'))